# Generated by Django 4.2.16 on 2024-11-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedownload',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
