# Generated by Django 4.2.16 on 2024-10-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
