# Generated by Django 4.2.16 on 2024-11-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0004_table_max_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='satisfaction',
            field=models.CharField(default='default_value', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='usefulness',
            field=models.CharField(default='default_value', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(default='default_value'),
            preserve_default=False,
        ),
    ]
