# Generated by Django 4.2.16 on 2024-11-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0005_remove_review_attendee_remove_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(default='option1', max_length=50),
            preserve_default=False,
        ),
    ]
