# Generated by Django 4.2.16 on 2024-11-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0006_review_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
