# Generated by Django 4.2.16 on 2024-11-22 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0002_filedownload_is_video'),
        ('registry_app', '0009_filedownload_display_name'),
    ]

    operations = [
    ]
