# Generated by Django 4.2.16 on 2024-11-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0010_merge_20241122_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedownload',
            name='file_name',
        ),
        migrations.AddField(
            model_name='filedownload',
            name='file',
            field=models.FileField(default='files/placeholder.txt', upload_to='files/'),
        ),
    ]
